W6D5/99catz/nested/catz/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

W6D5/99catz/nested/catz/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    
    COLORS = %w(black white orange brown grey).freeze
    
    validates :birth_date, presence: true 
    validates :color, presence: true
    validates :color, inclusion: COLORS
    validates :name, presence: true
    validates :sex, presence: true
    validates :sex, inclusion: %w(M F)
    validates :description, presence: true
    
    def age
        time_ago_in_words(birth_date)
    end

    

end

W6D5/99catz/nested/catz/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    
    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

      def new 
        @cat = Cat.new

        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        
        if @cat.save
            redirect_to cat_url(@cat)
        else
            flash.now[:errors] = @cat.errors.full_messages
            render :new
        end
    end

    def edit
        @cat = Cat.find(params [:id])
        render :edit
    end

    def update
        @cat = Cat.find(params [:id])

        if @cat.update_attributes(cat_params)
            redirect_to cat_url(@cat)
        else
            flash.now[:errors] = @cat.errors.full_messages
            render :edit
        end 
    end

    
    private

    def cat_params
        params.require(:cat).permit(:name, :age, :color, :birth_date, :sex, :description)
    end
end

W6D5/99catz/nested/catz/app/views/cats/edit.html.erb
<h1>Edit my Cat</h1>

<%= render 'shared/errors' %>
<%= render 'form', cat: @cat %>

W6D5/99catz/nested/catz/app/views/cats/index.html.erb
<h1>Alfredo's and Kien's Kitty Cats</h1>>
<ul>
    <% @cats.each do |cat|  %>
        <li><a href="<%=cat_url(cat) %>"><%= cat.name %></a></li>
    <% end %>
</ul>
    <a href="<%= new_cat_url %>">Create Cat</a>

W6D5/99catz/nested/catz/app/views/cats/new.html.erb
<h1>New Cat</h1>

<form action="<%=cats_url(@cat)%>" method="POST">
    <input type="hidden" name= "_method" value="POST">

    <label for="cat_name">name</label>
    <input 
        type="text"
        name="cat[name]"
        id="cat_name"
        value="<%= @cat.name %>">
    
    <label for="cat_birth_date">Birth Date</label>
    <input 
        type="date"
        name="cat[birth_date]"
        id="cat_birth_date"
        value="<%= @cat.birth_date %>">

    <label for="cat_colors">Color</label>
    <select name="cat[color]" id="cat_color">
        <option disabled selected>-- select color --</option>
        <%Cat::COLORS.each do |color| %>
            <option 
            <%= @cat.color == color ? "selected" : "" %>
            value="<%=color%>">
            <%= color.upcase %>
            </option>
            <% end %> 
    </select>
        
    <input 
        type="radio"
        name="cat[sex]"
        id="cat_sex_male"
        value="M"
        <%= @cat.sex == "M" ? "checked" : "" %>>
    <label for="cat_sex_male">Male</label>
    <input 
        type="radio"
        name="cat[sex]"
        id="cat_sex_female"
        value="M"
        <%= @cat.sex == "F" ? "checked" : "" %>>
    <label for="cat_sex_female">Female</label>
    <br>
    <br>
    <label>
    Description
    <textarea name="Cat[description]"><%= @cat.description %> </textarea>
    </label>

    <input type="submit" value="Create new Cat">
</form>

W6D5/99catz/nested/catz/app/views/cats/show.html.erb
<h1> <%= @cat.name %> </h1>

<table> 
    <tr>
        <th>Attribute</th>
        <th>Values</th>
    </tr>
    <% [:age, :birth_date, :color, :sex].each do |attribute_name|%>
        <tr>
            <td> <%=attribute_name %> </td>
            <td><%= @cat.send(attribute_name) %> </td>
        </tr>
    <% end %>
</table>

<a href="<%=edit_cat_url(@cat) %> ">Edit <%=@cat.name%></a>

W6D5/99catz/nested/catz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>